### ISSUE TITLE
Remove or use the `cycles` parameter in ic_http_client::request

### ISSUE THREAD

**Issue by MarioDfinity** [rocklabs-io/ic-web3#26]
`ic_http_client::request` is not using the [`cycles` parameter](https://github.com/rocklabs-io/ic-web3/blob/3166bb43cab1813c05757fb3867053c4b0ac7761/src/transports/ic_http_client.rs#L52). This is confusing for the user because it is exposed to users. Either remove it or use it and document how it can be used by the user.

**Comment by ccyanxyz** [comment]
Removed in PR: https://github.com/rocklabs-io/ic-web3/pull/27
