### ISSUE TITLE
HTTP Outcalls to Infura Goerli RPC using Rust [Error : RejectionCode: SysTransient ]

### ISSUE THREAD

**Issue by dipanshuhappy** [rocklabs-io/ic-web3#28]
Hey i am getting this error 
`
The http_request resulted into error. RejectionCode: SysTransient, Error: Failed to connect: error trying to connect: tcp connect error: deadline has elapsed
`
And i just called the eth_gasprice jsonrpc , which i copied from the examples

**Comment by cymqqqq** [comment]
I have the same question, maybe the reason is Goerli rpc can not support IPV6 network.

**Comment by dipanshuhappy** [comment]
> I have the same question, maybe the reason is Goerli rpc can not support IPV6 network.

true thats the issue , Infura doesn't support IPV6
